### ISSUE TITLE
4.25.4 Compile Errors

### ISSUE THREAD

**Issue by DevinSherry** [tomlooman/ActionRoguelike#1]
This first compile error is in SPlayerController.cpp. It can be fixed by adding the #include - 
**#include "Kismet/GameplayStatics.h"**

```
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SPlayerController.cpp(21): error C2653: 'UGameplayStatics': is not a class or namespace name
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SPlayerController.cpp(21): error C3861: 'SetGamePaused': identifier not found
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SPlayerController.cpp(38): error C2653: 'UGameplayStatics': is not a class or namespace name
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SPlayerController.cpp(38): error C3861: 'SetGamePaused': identifier not found
```
The second compile error occurs in SAnimInstance.h. It can be fixed by changing line 24 from _USActionComponent* ActionComp;_ to **class USActionComponent* ActionComp;**

```
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(25): error C2143: syntax error: missing ';' before '*'
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(25): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(25): error C2238: unexpected token(s) preceding ';'
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(15): error C2039: 'ActionComp': is not a member of 'USAnimInstance'
1>  D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(13): note: see declaration of 'USAnimInstance'
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(15): error C2618: illegal member designator in offsetof
1>  D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(15): note: offsetof has a builtin meaning; use /Zc:offsetof- to revert to old, non-conforming definition
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Intermediate\Build\Win64\UE4Editor\Inc\ActionRoguelike\SAnimInstance.gen.cpp(70): error C2039: 'ActionComp': is not a member of 'USAnimInstance'
1>  D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike/Public/SAnimInstance.h(13): note: see declaration of 'USAnimInstance'
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Intermediate\Build\Win64\UE4Editor\Inc\ActionRoguelike\SAnimInstance.gen.cpp(70): error C2618: illegal member designator in offsetof
1>  D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Intermediate\Build\Win64\UE4Editor\Inc\ActionRoguelike\SAnimInstance.gen.cpp(70): note: offsetof has a builtin meaning; use /Zc:offsetof- to revert to old, non-conforming definition
1>  [3/8] SAnimInstance.cpp
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Public\SAnimInstance.h(25): error C2143: syntax error: missing ';' before '*'
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Public\SAnimInstance.h(25): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Public\SAnimInstance.h(25): error C2238: unexpected token(s) preceding ';'
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Public\SAnimInstance.h(15): error C2039: 'ActionComp': is not a member of 'USAnimInstance'
1>  D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Public\SAnimInstance.h(13): note: see declaration of 'USAnimInstance'
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Public\SAnimInstance.h(15): error C2618: illegal member designator in offsetof
1>  D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Public\SAnimInstance.h(15): note: offsetof has a builtin meaning; use /Zc:offsetof- to revert to old, non-conforming definition
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SAnimInstance.cpp(19): error C2065: 'ActionComp': undeclared identifier
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SAnimInstance.cpp(30): error C2065: 'ActionComp': undeclared identifier
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SAnimInstance.cpp(32): error C2065: 'ActionComp': undeclared identifier
```
The third compile error occurs in SPowerupActor.cpp. This can be fixed by adding the #include - 
**#include "Net/UnrealNetwork.h"**

```
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SPowerupActor.cpp(71): error C2275: 'ASPowerupActor': illegal use of this type as an expression
1>D:\ActionRoguelike-UE4.25\ActionRoguelike-UE4.25\Source\ActionRoguelike\Private\SPowerupActor.cpp(71): error C3861: 'DOREPLIFETIME': identifier not found
```

**Comment by DevinSherry** [comment]
I provided solutions that worked for me to have this project compile on 4.25.4. This version comes from the epic games launcher, not from the engine source built from Github.

**Comment by tomlooman** [comment]
Thanks for this, I've just submitted the fixes for this into main.
